version: "3"
services:
  app:
    restart: on-failure
    build: ""
    depends_on:
      - postgres
    environment:
      PG_USER: postgres
      PG_PASSWORD: password
      PG_DB: tweet-db
      PG_HOST: postgres
      PG_PORT: 5432
      NODE_ENV: development
      PORT: 5000
    ports:
      - "5000:5000"

  postgres:
    image: postgres:11
    expose:
      - 5432
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tweet-db
